# add stages here 
stages:
  get_data:
    cmd: python src/stage_01_get_data.py --config=configs/config.yaml
    deps:
      - src/stage_01_get_data.py
      - src/utils/common.py
      - configs/config.yaml  # By adding this config file in dependecies, DVC can track changes
    outs:
      - data/data.xml
  prepare_data:
    cmd: python src/stage_02_prepare_data.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_02_prepare_data.py
      - src/utils/common.py
      - src/utils/data_mgmt.py
      - configs/config.yaml  
      - data/data.xml
    params:
      - prepare.seed
      - prepare.split # By using params.yaml file, it gets the prameters
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
  featurize:
    cmd: python src/stage_03_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_03_featurization.py
      - src/utils/common.py
      - src/utils/featurize.py
      - configs/config.yaml  
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl
  train:
    cmd: python src/stage_04_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_04_train.py
      - src/utils/common.py
      - configs/config.yaml  
      - artifacts/features/train.pkl
    params:
      - train.seed
      - train.n_estimators
      - train.min_split
    outs:
      - artifacts/saved_model/model.pkl

  evaluate:
    cmd: python src/stage_05_evaluate.py --config=configs/config.yaml
    deps: 
      - src/stage_05_evaluate.py
      - src/utils/common.py
      - configs/config.yaml  
      - artifacts/features/test.pkl
      - artifacts/saved_model/model.pkl
    metrics: 
      - scores.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr
    